version: '3'

services: 
    
    ride-sharing-service:
        build: ./ride-sharing-service/
        restart: always

    nginx:
        build: ./nginx/
        ports: 
            - 7000:80
        depends_on: 
            - ride-sharing-service
    
